### ISSUE TITLE
Q: how does it work?

### ISSUE THREAD

**Issue by mwpowellhtx** [Brominum/Bro_Modular_Warehouse#1]
is it compositions, to parts actually 'lock' or attach into place? interesting concept, though...

**Comment by Brominum** [comment]
These are individual pieces placed the 3den Editor in ArmA 3. An example composition is available, related links:
Object: https://steamcommunity.com/sharedfiles/filedetails/?id=2958273599
Composition: https://steamcommunity.com/sharedfiles/filedetails/?id=2958282759
